# Generated by Django 3.1.2 on 2020-11-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=' ', max_length=255, verbose_name='Name'),
        ),
    ]
