# Generated by Django 3.1.2 on 2020-10-22 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Post title', max_length=170, verbose_name='Title')),
                ('body', models.TextField(help_text='Post content', verbose_name='Body')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Published on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('slug', models.URLField(verbose_name='Slug')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]