# Generated by Django 3.1.2 on 2020-11-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='category_name')),
                ('slug', models.URLField(max_length=50, unique=True, verbose_name='category_url')),
                ('description', models.CharField(max_length=150, verbose_name='category_description')),
            ],
        ),
    ]
